Modificando Nome/ Proj-Casa-Fabiana de Oliveira
reprograma/On4-git-e-github pull request #48
Opened 2019-11-13 16:57 UTC by tavarinasp

2019-11-15 21:56 UTC, MaichiLydia requested changes

2019-11-15 21:56 UTC, MaichiLydia commented on 7-exercicio-projeto-casa/index.html
> +          <img class="container__aluna-img" src="https://avatars0.githubusercontent.com/u/54474786?s=460&v=4" alt="nomeAluna">
Oi Fabiana, tudo bom ?
Faltou preencher o seu nome no alt="nomeAluna" da tag <img /> e você preencheu o da fabiola, tem que preencher no seu em Fabiana.

2019-11-15 22:57 UTC, tavarinasp commented on 7-exercicio-projeto-casa/index.html
> +          <img class="container__aluna-img" src="https://avatars0.githubusercontent.com/u/54474786?s=460&v=4" alt="nomeAluna">
oieee 
vou fazer isso

2019-11-16 21:37 UTC, MaichiLydia commented on 7-exercicio-projeto-casa/index.html
> +          <img class="container__aluna-img" src="https://avatars0.githubusercontent.com/u/54474786?s=460&v=4" alt="nomeAluna">
perfeito !!

2019-11-16 21:37 UTC, merged